version: '3.8'

networks:
  gateway:
    external: true

services:
  ui:
    image: node:16-alpine
    working_dir: /web
    env_file: .env
    entrypoint:
      - /bin/sh
      - "-c"
      - "yarn install && exec yarn dev --host 0.0.0.0 --port 3000"
    volumes:
      - .:/web

  proxy:
    image: bitnami/nginx:latest
    volumes:
      - ./proxy:/opt/bitnami/nginx/conf/server_blocks:ro
    environment:
      - NGINX_HTTP_PORT_NUMBER=8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firebase-test.rule=Host(`firebase-test.localhost`)"
      - "traefik.http.routers.firebase-test.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.firebase-test.loadbalancer.server.port=8000"
    networks:
      - default
      - gateway
    restart: unless-stopped
